version: '3.8' 

services:
  # --- Сервис приложения ---
  telegram-mail-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-mail-system
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped

  # --- Сервис Nginx ---
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"  # HTTPS порт
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL сертификаты
    depends_on:
      - telegram-mail-system
    restart: unless-stopped

volumes:
  app_data:
  app_logs: